server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: pinet-rest
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 指定默认数据源
      primary: master
      druid:
        min-idle: 10
        max-pool-prepared-statement-per-connection-size: 20
        validation-query-timeout: 30000
        test-while-idle: true
        time-between-eviction-runs-millis: 5000
        max-active: 400
        validation-query: SELECT 1 FROM DUAL
        max-wait: 60000
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        test-on-borrow: false
        pool-prepared-statements: true
        initial-size: 20
        min-evictable-idle-time-millis: 300000
        test-on-return: false
        filter: stat,wall,slf4j
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/qingshi?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://127.0.0.1:3306/xinjiang-shop?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.91
    password: qwer1234
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms

  activemq:
    broker-url: tcp://192.168.1.91:61616
    user: admin
    password: admin
    pool:
      enabled: true #连接池启动
      max-connections: 10 #最大连接数


mybatis-plus:
  mapper-locations: classpath*:com/pinet/rest/mapper/xml/*.xml
  configuration:
    ## 自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体类扫描
  global-config:
    banner: false
    # 逻辑删除配置
    db-config:
      ## 逻辑删除字段
      logic-delete-field: del_flag
      ## 逻辑删除未删除值
      logic-not-delete-value: 0
      ## 配置逻辑删除字段为1是删除
      logic-delete-value: 1


sms:
  code:
    # 验证码 有效期10分钟
    expire: 600

# 微信开发配置
wx:
  miniapp:
    appid: wx2cf61e93a478f54f
    secret: 8cb2cf16e9334e123de200549a7e3afb

#oss配置
oss:
  qiniu:
    access_key: qSK4UbqoR7gb0gkmHcwBeY3K3GoiW1UmDm01CMNx
    secret_key: eE83WK1Bo3iR7YyMfyTwsqTJL3HFFz14dNiimBDl
    bucket: testpinets
    url: https://image.ypxlbz.com




social:
  weixin:
    app:
      appid: wx2cf61e93a478f54f
      secret: f8627072cc1c0f3c8a366ffa61ab750d
      mch_id: 1502776411
      notify_url: http://testxingjianghouse.ypxlbz.com/house/qingshi/api/notify/order/wxApp/pay
      key: ZHANGSHUOwudi1234567891011121314
      p12url: /www/apiclient_cert.p12
    mini:
      appid: wx2cf61e93a478f54f
      secret: 8cb2cf16e9334e123de200549a7e3afb
      mch_id: 1502776411
      notify_url: http://testxingjianghouse.ypxlbz.com/house/qingshi/api/notify/order/wxMini/pay
      key: ZHANGSHUOwudi1234567891011121314
      p12url: /www/apiclient_cert.p12
  alipay:
    app:
      appid: 2018042302596042
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhAzKN13ZipHKt4Gji1PqMl4zyc5C1vTnPPKyLYn61v2ot9/aFdlxo/hoZResONBtjmUhT4FwBAlqyABTa6EU7gsBzT4hKtgaLZka33faBHd90XIAAome/B94UrJtQtsf6ND5suNI46IAB5IZ7iE7Xi0DYGNvukFaXMMgdVOoi6w6O1QoCutuWUZgU77SWrYjnh76YexuiGCA80VvUr7TAlip+xKa9lgZa5p4EBCya9/yhrhTfS2YSYSRbOWZ4hE/t/C8FH+QKdPb7wsq0sQ7e9Rv5Zcr1YfcJu3kvNjiLHCSu/fe8uGTTbF1IwhFhuTqcDLZAoJzBSyxR3M6/9uJFwIDAQAB
      private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCEDMo3XdmKkcq3gaOLU+oyXjPJzkLW9Oc88rItifrW/ai339oV2XGj+GhlF6w40G2OZSFPgXAECWrIAFNroRTuCwHNPiEq2BotmRrfd9oEd33RcgACiZ78H3hSsm1C2x/o0Pmy40jjogAHkhnuITteLQNgY2+6QVpcwyB1U6iLrDo7VCgK625ZRmBTvtJatiOeHvph7G6IYIDzRW9SvtMCWKn7Epr2WBlrmngQELJr3/KGuFN9LZhJhJFs5ZniET+38LwUf5Ap09vvCyrSxDt71G/llyvVh9wm7eS82OIscJK7997y4ZNNsXUjCEWG5OpwMtkCgnMFLLFHczr/24kXAgMBAAECggEAf4ZGh7/Hxg3UIvI8ueJZazkUdJEQdb1fz7lmH5qAN74SgTjayX0MRVkxoGeDN/75vqmlyL1tK0jY6bt+1JNkvhq9K7QTnefDKEQS8rsxPl0TkgCxR8IWWtAdiGeuIwGxSEsAyiS7kLIzqxwKlLFdPy7jcuO008AnfywmHYikXfWWt5TNwYkEih3gO6OJk90YFLPpZrHf9UUDPjz3f4pTGy17dCa6c7XWS9tDojlgZO368CEXSS3hwg3oTwu+8FOCfoX1I262DkpsQg1N+pzghsvynkJAra5vvGsp44hu/DZN834NWLnem3rq/FUR8c8rViNN87HX7h7ZuWRATunMMQKBgQDZr+2PiTeWllv3TvqW18UEmsYlCIzsyZBcmTmgeTnLp+kuO9C+4atwA31itbPm+PIBttqkzTxQGcnYzCqgn/FTP9MNorOLIdtBFZS2gbbOCSWdterx6hhbF8sbt42yGb2YBh2LJu1pqAKiNd5I3TSdaV0cI9Jd/l3vyDz2bPI8+QKBgQCbSmgbbHGkIPz3ZdnY2EfUdso4mit3u99igufrY0dJQNh77Cl4mdg2USMG/OYnaAwivZuJMuqygScZswyQy/lZXhHQuQKt4bWWmLDfl+bjVdNHfjDsry8CCmM/AUOGWrMZmv3CsKiUfUoQ3Am+ot1X4bigfdLVJaZzMD3BiqfKjwKBgCaHzTSqxPwSgRS1FgW9C1JVUt0bNlZzFupM9LZCvsgdYFiencQrjXy2IWtnXgBz7+H9y5V//jzvU5rcCG+F3+EsWt7+/WiTBYvvlfL34rN1SwMvP/axyL3W6ExvoNT1WWmfK3uF2F/rLQwpHL8o6Dc0fxaMAKBCdb4LYz766aWBAoGBAIEUQSMCaheeYAcYfxLS/Cnrr72K0LTO0ijlXPd450lJgGjJbdNUNbc4jCAD2R9KSkQaTQ2m6BUGa8Td4oT9Nz+EhNR05Hg6VCFgvCyu6/ltXphfmTUzjKRqlAJL/5/PBm4zOdk51HbRCd6nt+XhJJEnC7tDuxr3F7tJjxuwMDabAoGBAL7qoOQCyGoiDef6Ig1g1hi0AGvgaR4/8k6X6imt+gY7yy/wQJbnCVYWpVrKoIyIz0f5sWKfzaBCNoWiFwrzYCVYFngQ+/CJ1kkiN/3ruZ2T84uW0D9DG22NjkABuraQ33MC8jv+QIOlfMyeR5IZ31+jcZ4JxCyysFuM8DBrxjj+
      sellerid: 13399722222@163.com
      partnerid: 2088031797087204
      notify-url: http://testxingjianghouse.ypxlbz.com/house/qingshi/api/notify/order/aliApp/pay
      app-cert-url: /usr/local/project/cert/appCertPublicKey_2018042302596042.crt
      root-cert-url: /usr/local/project/cert/alipayRootCert.crt
      public-cert-url: /usr/local/project/cert/alipayCertPublicKey_RSA2.crt

kry:
  projectName: kry-open-plantform-demo
  projectVersion: @project.version@
  #url: https://openapi.keruyun.com
  url: https://gldopenapi.keruyun.com
  appKey: 8a455f1d88a83e33b15f3ebfce97f2a4
  appSecret: cc04a0564e4b5f069ec499cf04b2308e