server:
  port: 8090
spring:
  application:
    name: pinet-rest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      druid:
        min-idle: 10
        max-pool-prepared-statement-per-connection-size: 20
        validation-query-timeout: 30000
        test-while-idle: true
        time-between-eviction-runs-millis: 5000
        max-active: 400
        validation-query: SELECT 1 FROM DUAL
        max-wait: 60000
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        test-on-borrow: false
        pool-prepared-statements: true
        initial-size: 20
        min-evictable-idle-time-millis: 300000
        test-on-return: false
        filter: stat,wall,slf4j
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/qingshi?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://127.0.0.1:3306/xjs?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password: qwer1234
    port: 6379



mybatis-plus:
  mapper-locations: classpath*:com/pinet/mapper/xml/*.xml
  configuration:
    ## 自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体类扫描
  global-config:
    banner: false
    # 逻辑删除配置
    db-config:
      ## 逻辑删除字段
      logic-delete-field: del_flag
      ## 配置逻辑删除字段为1是删除
      logic-not-delete-value: 0
      ## 逻辑删除未删除值
      logic-delete-value: 1


