server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.91:3306/xjs?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 连接池的配置信息
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,slf4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

  redis:
    database: 0
    host: 127.0.0.1
    password: qwer1234
    port: 8379



mybatis-plus:
  mapper-locations: classpath*:com/pinet/mapper/xml/*.xml
  configuration:
    ## 自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体类扫描
  global-config:
    # 逻辑删除配置
    db-config:
      ## 逻辑删除字段
      logic-delete-field: deleted
      ## 配置逻辑删除字段为1是删除
      logic-not-delete-value: 0
      ## 逻辑删除未删除值
      logic-delete-value: 1
    banner: false
